version: "3.8"

services:
  db:
    image: postgres:14.5
    container_name: next-newsletter_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=next-newsletter_dev
    ports:
      - "5432:5432"