name: Test

on: 
  pull_request:
    paths: 
      - nextjs-12/**

jobs:
  test:
    name: Run linters and tests Next.js 12
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'nextjs-12/package-lock.json'

      - name: Install dependencies
        run: 'cd nextjs-12 && npm ci'

      - name: Run linter
        run: 'cd nextjs-12 && npm run lint'

      - name: Run unit tests
        run: 'cd nextjs-12 && npm run test:coverage'
