name: Test Remix

on:
  pull_request:
    paths:
      - remix/**

jobs:
  test-remix:
    name: Run linters and tests Remix
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remix

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{github.token}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "remix/package-lock.json"

      - name: Create env file
        run: |
          touch .env
          echo NODE_ENV=development >> .env
          echo GOOGLE_CLIENT_ID=274093098276-7sar8nsfcpsge9ni7p4nbi5rui6ed3dn.apps.googleusercontent.com >> .env
          echo GOOGLE_CLIENT_SECRET=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 >> .env
          echo SESSION_NAME=__session >> .env
          echo SESSION_SAMESITE=lax >> .env
          echo SESSION_PATH=/ >> .env
          echo SESSION_HTTPONLY=1 >> .env
          echo SESSION_SECRETS=veryscret >> .env
          echo SESSION_SECURE=1 >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --coverage
